language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t thousanda/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true thousanda/docker-react npm run test